name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repozitoriyani klonlash
        uses: actions/checkout@v3

      - name: Flutterni o'rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Paketlarni o'rnatish
        run: flutter pub get

      - name: Testlarni ishga tushirish
        run: flutter test